jenkins:
  nodes:
  - permanent:
      labelString: "docker-build"
      launcher:
        ssh:
          credentialsId: "cfaf31c8-22ea-487d-9d6d-b7dd77b624f5"
          host: "13.77.107.72"
          jvmOptions: "-Xmx256m -Xms256m"
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeTB1LA7FnUI8kNrY8zVx/Ywy1RN4tJj11W9QWFWTr6gAJgSNEneKIa8hnjZEPddYOIsBOQ9VSvgXYGFRKEFXW23zskuWEyCqSZ/e7RTw2VTCh5nfUZlX1eG7iujn1mpineX/+hRR7HtxDM9MPhpbrq6HVjXuSx8mex9vu4p20ZVZkewedmtG2+qYDDTsv8uw0kX+kkyRuE6An14omsCQ+8mJ17zQnGXN2CnrXXMOWbgH9BC8RZUvNZOzNY1JkWf9EqY2Tz3YJPgUM+9qVj3/BEjGopEIUT/jDuk2NnOo+V1GT8aWzwmBjv91F7wgjuQ72cV8GeSbxz0utQ9isuMkp"
      mode: EXCLUSIVE
      name: "ubuntu1804-azr-ef-fmlw3"
      nodeDescription: "2vCPU, 8GB RAM, Hosted @ Azure"
      remoteFS: "/home/genie.cbi/jenkins-agent"
      numExecutors: 2
      nodeProperties:
      - watcher:
          offlineAddresses: "releng@eclipse.org"
          onlineAddresses: "releng@eclipse.org"

unclassified:
  slackNotifier:
    teamDomain: "eclipsefoundation"
    tokenCredentialId: "03a52394-e33f-46fc-be2a-222bf8e9a58f"

  prometheusConfiguration:
    appendParamLabel: false
    appendStatusLabel: false
    collectCodeCoverage: false
    collectDiskUsage: true
    collectNodeStatus: true
    collectingMetricsPeriodInSeconds: 120
    countAbortedBuilds: true
    countFailedBuilds: true
    countNotBuiltBuilds: true
    countSuccessfulBuilds: true
    countUnstableBuilds: true
    defaultNamespace: ""
    disabledMetricConfig:
      entries:
      - regexDisabledMetric:
          regex: "jenkins_builds_last_stage_duration.*"
      - regexDisabledMetric:
          regex: "jvm_.*"
      - regexDisabledMetric:
          regex: "vm_memory.*"
      - regexDisabledMetric:
          regex: "jenkins_builds_discard_active.*"
    fetchTestResults: true
    jobAttributeName: "jenkins_job"
    path: "prometheus"
    perBuildMetrics: false
    processingDisabledBuilds: false
    useAuthenticatedEndpoint: false