apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "openpass-cache-storage"
  namespace: "openpass"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "200Gi"
  storageClassName: cephfs-2repl